# -*- coding: utf-8 -*-
"""Bilingual copy for the Technical Consultancy pages.

Every string is a (en, ar) pair keyed by its data-i18n key. The Arabic is
DRAFT machine-assisted copy for Afzal's review, like every other Arabic block
on this site. No fee, timeline, licence, certification or savings figure is
stated anywhere: fees are quoted per request, and the policy says so.
"""

SECTORS = ['ups', 'firefighting', 'hvac', 'isolated-power', 'facility-management', 'airports']

# Shared strings ------------------------------------------------------------
S = {
    # nav / breadcrumb
    'service_consultancy': ('Technical Consultancy', 'الاستشارات الفنية'),
    'cons_bc_hub': ('Technical Consultancy', 'الاستشارات الفنية'),
    'cons_overline': ('Consultancy', 'الاستشارات'),
    'cons_cta_request': ('Request a Consultation', 'اطلب استشارة'),
    'cons_cta_wa': ('Ask on WhatsApp', 'اسأل عبر واتساب'),
    'cons_cta_policy': ('Read the Consultancy Policy', 'اقرأ سياسة الاستشارات'),
    'cons_related': ('Related', 'ذات صلة'),

    # hub
    'cons_hub_h1': ('Technical Consultancy for Facilities Across Saudi Arabia',
                    'الاستشارات الفنية للمنشآت في جميع أنحاء المملكة'),
    'cons_hub_sub': ('A clear start-to-finish project plan with reference costing, so you decide on the right solution before you spend.',
                     'خطة مشروع واضحة من البداية إلى النهاية مع تكلفة مرجعية، لتقرر الحل المناسب قبل أن تُنفق.'),
    'cons_why_h': ('Why book a consultancy first?', 'لماذا تبدأ بالاستشارة؟'),
    'cons_why_p1': ('Most expensive mistakes in a facility project are made early: the wrong system size, the wrong technology, a scope that ignores the site, or a plan that cannot be maintained. A consultancy puts the technical questions and the cost questions on the table before equipment is ordered.',
                    'تحدث معظم الأخطاء المكلفة في مشاريع المنشآت مبكراً: حجم نظام غير مناسب، أو تقنية غير مناسبة، أو نطاق عمل يتجاهل واقع الموقع، أو خطة لا يمكن صيانتها. تضع الاستشارة الأسئلة الفنية وأسئلة التكلفة على الطاولة قبل طلب أي معدات.'),
    'cons_why_p2': ('It is a paid, scoped service. The work depends on your site, your sector and the stage your project is at, so we agree the scope and fee with you in writing before we start.',
                    'هي خدمة مدفوعة ومحددة النطاق. يعتمد العمل على موقعك وقطاعك والمرحلة التي بلغها مشروعك، لذلك نتفق معك كتابياً على النطاق والأتعاب قبل أن نبدأ.'),
    'cons_sectors_h': ('Choose your sector', 'اختر قطاعك'),
    'cons_sectors_o': ('Sectors We Cover', 'القطاعات التي نغطيها'),
    'cons_recv_o': ('What You Receive', 'ما ستحصل عليه'),
    'cons_recv_h': ('A plan you can act on', 'خطة يمكنك العمل بها'),
    'cons_recv_1t': ('Site and requirements review', 'مراجعة الموقع والمتطلبات'),
    'cons_recv_1d': ('We review your site conditions, drawings and documents, and what you need the facility to do.',
                     'نراجع ظروف موقعك ومخططاتك ومستنداتك وما تحتاجه من المنشأة.'),
    'cons_recv_2t': ('Findings and options', 'النتائج والخيارات'),
    'cons_recv_2d': ('A written summary of what we found, the realistic options, and where money can be saved or risk reduced.',
                     'ملخص مكتوب لما وجدناه والخيارات الواقعية والمواضع التي يمكن فيها توفير المال أو تقليل المخاطر.'),
    'cons_recv_3t': ('Start-to-finish project plan', 'خطة مشروع من البداية إلى النهاية'),
    'cons_recv_3d': ('The stages of the project in order, from design and procurement to installation, testing and handover.',
                     'مراحل المشروع بالترتيب، من التصميم والتوريد إلى التركيب والاختبار والتسليم.'),
    'cons_recv_4t': ('Reference costing', 'التكلفة المرجعية'),
    'cons_recv_4d': ('An indicative cost reference for planning and budgeting, prepared from the information available at the time.',
                     'مرجع تكلفة استرشادي للتخطيط وإعداد الميزانية، يُعدّ من المعلومات المتاحة وقت إعداده.'),
    'cons_recv_5t': ('How the work was done', 'كيف أُنجز العمل'),
    'cons_recv_5d': ('A plain explanation of the method, assumptions and standards behind the advice, so your team or another contractor can follow it.',
                     'شرح واضح للمنهجية والافتراضات والمعايير التي بُنيت عليها التوصيات، ليتمكن فريقك أو مقاول آخر من متابعتها.'),
    'cons_proc_o': ('How It Works', 'كيف تتم الخدمة'),
    'cons_proc_h': ('From your request to your plan', 'من طلبك إلى خطتك'),
    'cons_proc_1t': ('Send your request', 'أرسل طلبك'),
    'cons_proc_1d': ('Tell us the sector, the site and what you are trying to achieve.',
                     'أخبرنا بالقطاع والموقع وما تريد تحقيقه.'),
    'cons_proc_2t': ('Scope and quotation', 'النطاق وعرض السعر'),
    'cons_proc_2d': ('We reply with a written scope and fee for your specific situation.',
                     'نرد عليك بنطاق عمل وأتعاب مكتوبة لحالتك تحديداً.'),
    'cons_proc_3t': ('Review and site work', 'المراجعة والعمل الميداني'),
    'cons_proc_3d': ('We review your documents and, where the scope needs it, the site itself.',
                     'نراجع مستنداتك، وعند الحاجة نراجع الموقع نفسه.'),
    'cons_proc_4t': ('Plan and costing delivered', 'تسليم الخطة والتكلفة'),
    'cons_proc_4d': ('You receive the written project plan with reference costing and the method behind it.',
                     'تستلم خطة المشروع المكتوبة مع التكلفة المرجعية والمنهجية التي بُنيت عليها.'),
    'cons_price_o': ('Fees', 'الأتعاب'),
    'cons_price_h': ('How pricing works', 'كيف يتم التسعير'),
    'cons_price_p1': ('Consultancy is a paid service and is not free. The fee depends on your site, your sector, the size of the facility and the stage of the project, so there is no single price list.',
                      'الاستشارة خدمة مدفوعة وليست مجانية. تعتمد الأتعاب على موقعك وقطاعك وحجم المنشأة ومرحلة المشروع، لذلك لا توجد قائمة أسعار موحدة.'),
    'cons_price_p2': ('Send a request and we will reply with a written quotation in Saudi riyals stating the scope, the deliverables and the fee. Nothing starts until you accept it in writing.',
                      'أرسل طلباً وسنرد عليك بعرض سعر مكتوب بالريال السعودي يوضح النطاق والمخرجات والأتعاب. لا يبدأ أي عمل قبل قبولك الكتابي.'),
    'cons_indep_o': ('Transparency', 'الشفافية'),
    'cons_indep_h': ('Our interest, stated up front', 'مصلحتنا، معلنة مسبقاً'),
    'cons_indep_p': ('Black Arrow also supplies and installs some of the equipment discussed in these sectors. Where a recommendation involves something we supply, the report says so, and you are free to take the plan to any other contractor.',
                     'تقوم بلاك أرو أيضاً بتوريد وتركيب بعض المعدات المذكورة في هذه القطاعات. وعندما تتعلق التوصية بشيء نوفره، يذكر التقرير ذلك، وأنت حر في أخذ الخطة إلى أي مقاول آخر.'),
    'cons_faq_h': ('Frequently Asked Questions', 'الأسئلة الشائعة'),
    'cons_faq_o': ('Common Questions', 'أسئلة شائعة'),
    'cons_q1': ('Is the consultancy free?', 'هل الاستشارة مجانية؟'),
    'cons_a1': ('No. Consultancy is a paid service. We quote a fee in writing after we receive your request, and work starts only after you accept it.',
                'لا. الاستشارة خدمة مدفوعة. نرسل عرض أتعاب مكتوباً بعد استلام طلبك، ولا يبدأ العمل إلا بعد قبولك.'),
    'cons_q2': ('How much does it cost?', 'كم تبلغ التكلفة؟'),
    'cons_a2': ('It depends on the site, the sector, the size of the facility and the scope you need. We provide the cost on receiving your request rather than publishing a fixed price.',
                'تعتمد على الموقع والقطاع وحجم المنشأة والنطاق المطلوب. نقدم التكلفة بعد استلام طلبك بدلاً من نشر سعر ثابت.'),
    'cons_q3': ('What do I receive at the end?', 'ماذا أستلم في النهاية؟'),
    'cons_a3': ('A written start-to-finish project plan, a reference costing for planning, and an explanation of how the consultancy was carried out.',
                'خطة مشروع مكتوبة من البداية إلى النهاية، وتكلفة مرجعية للتخطيط، وشرحاً لكيفية تنفيذ الاستشارة.'),
    'cons_q4': ('Is the reference costing a binding quotation?', 'هل التكلفة المرجعية عرض سعر ملزم؟'),
    'cons_a4': ('No. It is an indicative reference for planning and budgeting. A binding price arises only from a signed contract or purchase order.',
                'لا. هي مرجع استرشادي للتخطيط وإعداد الميزانية. لا ينشأ سعر ملزم إلا من عقد موقع أو أمر شراء.'),
    'cons_q5': ('Do I have to buy equipment or installation from Black Arrow?', 'هل يجب أن أشتري المعدات أو التركيب من بلاك أرو؟'),
    'cons_a5': ('No. The consultancy is a separate service. You may use the plan with any contractor.',
                'لا. الاستشارة خدمة مستقلة. يمكنك استخدام الخطة مع أي مقاول.'),
    'cons_cta_h': ('Ready to plan your project?', 'هل أنت مستعد لتخطيط مشروعك؟'),
    'cons_cta_sub': ('Send your request and we will reply with the scope and fee.', 'أرسل طلبك وسنرد عليك بالنطاق والأتعاب.'),
    'cons_sector_lead': ('Consultancy for', 'استشارات'),
    'cons_covers_o': ('What It Covers', 'ما تغطيه الاستشارة'),
    'cons_covers_note': ('The exact scope depends on your site and is agreed in writing before work starts.',
                         'يعتمد النطاق الدقيق على موقعك ويُتفق عليه كتابياً قبل بدء العمل.'),
    'cons_view_service': ('View the related service', 'عرض الخدمة ذات الصلة'),
    'cons_all_sectors': ('All consultancy sectors', 'جميع قطاعات الاستشارات'),
    'cons_learn_more': ('Learn more', 'اعرف المزيد'),
}

# Sector pages ----------------------------------------------------------------
SECTOR = {
    'ups': dict(
        name=('UPS & Power Backup', 'أنظمة UPS والطاقة الاحتياطية'),
        meta_title=('UPS Consultancy Saudi Arabia | Sizing, Battery & Project Plan', 'استشارات أنظمة UPS في السعودية | الحجم والبطاريات وخطة المشروع'),
        meta_desc=('Paid UPS consultancy in Saudi Arabia: load and runtime assessment, topology, battery choice and a start-to-finish project plan with reference costing.',
                   'استشارات مدفوعة لأنظمة UPS في السعودية: تقييم الأحمال وزمن التشغيل والتقنية واختيار البطاريات وخطة مشروع كاملة مع تكلفة مرجعية.'),
        h1=('UPS Consultancy for Critical Facilities', 'استشارات أنظمة UPS للمنشآت الحرجة'),
        sub=('Get the size, technology and budget right before you buy.', 'اضبط الحجم والتقنية والميزانية قبل أن تشتري.'),
        intro=('A UPS that is oversized wastes capital, and one that is undersized fails when you need it. The consultancy works from your real loads, your required runtime and your site conditions to a plan you can budget and maintain.',
               'يهدر نظام UPS كبير الحجم رأس المال، ويفشل النظام الأصغر من اللازم عند الحاجة. تنطلق الاستشارة من أحمالك الفعلية وزمن التشغيل المطلوب وظروف موقعك لتصل إلى خطة يمكنك تمويلها وصيانتها.'),
        covers=[
            (('Load and criticality assessment', 'تقييم الأحمال ومدى الأهمية'), ('Which loads must never drop, which can wait, and how much power each really needs.', 'أي الأحمال لا يجوز أن تنقطع، وأيها يمكن أن ينتظر، وكم تحتاج كل منها فعلاً.')),
            (('Sizing and runtime', 'الحجم وزمن التشغيل'), ('Capacity and battery runtime matched to your requirement, with room for growth.', 'سعة وزمن تشغيل بطاريات مناسبان لمتطلباتك مع مجال للنمو.')),
            (('Topology and redundancy', 'التقنية والتكرار'), ('Online, modular or parallel designs, and what level of redundancy the site actually justifies.', 'تصاميم أونلاين أو معيارية أو متوازية، ومستوى التكرار الذي يبرره الموقع فعلاً.')),
            (('Battery technology and lifetime cost', 'تقنية البطاريات وتكلفة العمر التشغيلي'), ('VRLA versus lithium-ion compared over the life of the system, including replacement.', 'مقارنة VRLA بأيونات الليثيوم على مدى عمر النظام بما فيه الاستبدال.')),
            (('Maintenance and testing plan', 'خطة الصيانة والاختبار'), ('Maintenance, load-bank testing and battery replacement planned in advance instead of after a failure.', 'صيانة واختبار حمل واستبدال بطاريات مخطط لها مسبقاً بدلاً من ما بعد العطل.')),
        ],
        service=('/services/ups-power-backup/', ('UPS Solutions', 'حلول UPS')),
        q=(('Can the consultancy cover an existing UPS?', 'هل تشمل الاستشارة نظام UPS قائماً؟'),
           ('Yes. We can review an existing installation, its loads, batteries and maintenance history, and advise whether to keep, upgrade or replace it.',
            'نعم. يمكننا مراجعة تركيب قائم وأحماله وبطارياته وسجل صيانته، وتقديم المشورة بالإبقاء عليه أو ترقيته أو استبداله.')),
        wa=('UPS consultancy', 'استشارة UPS'),
    ),
    'firefighting': dict(
        name=('Firefighting Systems', 'أنظمة مكافحة الحريق'),
        meta_title=('Fire Protection Consultancy Saudi Arabia | Systems & Project Plan', 'استشارات أنظمة مكافحة الحريق في السعودية | الأنظمة وخطة المشروع'),
        meta_desc=('Paid fire protection consultancy in Saudi Arabia: detection and suppression review, NFPA and Civil Defense requirements, and a project plan with reference costing.',
                   'استشارات مدفوعة لأنظمة مكافحة الحريق في السعودية: مراجعة الكشف والإطفاء ومتطلبات NFPA والدفاع المدني وخطة مشروع مع تكلفة مرجعية.'),
        h1=('Fire Protection Consultancy for Facilities', 'استشارات الحماية من الحريق للمنشآت'),
        sub=('A clear view of what your facility needs, and what it will cost, before design starts.', 'رؤية واضحة لما تحتاجه منشأتك وتكلفته قبل بدء التصميم.'),
        intro=('Fire protection is regulated and unforgiving. The consultancy reviews your facility and existing systems against the requirements that apply, and turns the findings into a staged plan and a budget.',
               'الحماية من الحريق مجال منظم ولا يقبل التهاون. تراجع الاستشارة منشأتك وأنظمتها القائمة وفق المتطلبات المطبقة، وتحوّل النتائج إلى خطة مرحلية وميزانية.'),
        covers=[
            (('Risk and hazard review', 'مراجعة المخاطر والأخطار'), ('What is stored, how the space is used, and what that means for protection.', 'ما يُخزَّن وكيف يُستخدم المكان وما يعنيه ذلك للحماية.')),
            (('Detection and suppression options', 'خيارات الكشف والإطفاء'), ('Addressable alarm, sprinklers, gaseous or water-mist suppression compared for your space.', 'المقارنة بين الإنذار العنواني والرشاشات والإطفاء الغازي أو بالرذاذ المائي لمكانك.')),
            (('Requirements review', 'مراجعة المتطلبات'), ('Applicable NFPA and Saudi Civil Defense requirements identified up front.', 'تحديد متطلبات NFPA والدفاع المدني السعودي المطبقة منذ البداية.')),
            (('Gap review of existing systems', 'مراجعة الفجوات في الأنظمة القائمة'), ('Where an installed system falls short, and the order in which to fix it.', 'مواضع القصور في النظام المركّب وترتيب معالجتها.')),
            (('Testing and maintenance plan', 'خطة الفحص والصيانة'), ('An inspection and maintenance routine that keeps the system ready and documented.', 'برنامج فحص وصيانة يُبقي النظام جاهزاً وموثقاً.')),
        ],
        service=('/services/firefighting-systems/', ('Firefighting Systems', 'أنظمة مكافحة الحريق')),
        q=(('Does the consultancy replace Civil Defense approval?', 'هل تغني الاستشارة عن اعتماد الدفاع المدني؟'),
           ('No. The consultancy is advice and planning. Approvals, permits and certifications required by the authorities remain your responsibility, and we tell you which ones apply.',
            'لا. الاستشارة نصح وتخطيط. تبقى الموافقات والتصاريح والشهادات التي تشترطها الجهات المختصة مسؤوليتك، ونوضح لك ما ينطبق منها.')),
        wa=('fire protection consultancy', 'استشارة الحماية من الحريق'),
    ),
    'hvac': dict(
        name=('HVAC', 'التكييف والتهوية'),
        meta_title=('HVAC Consultancy Saudi Arabia | Load, Energy & Project Plan', 'استشارات التكييف في السعودية | الأحمال والطاقة وخطة المشروع'),
        meta_desc=('Paid HVAC consultancy in Saudi Arabia: load review, VRF/VRV and chiller options, energy and controls, and a project plan with reference costing.',
                   'استشارات مدفوعة للتكييف في السعودية: مراجعة الأحمال وخيارات VRF/VRV والمبردات والطاقة والتحكم وخطة مشروع مع تكلفة مرجعية.'),
        h1=('HVAC Consultancy for Commercial Buildings', 'استشارات التكييف للمباني التجارية'),
        sub=('Choose the right system and control strategy before you commit the budget.', 'اختر النظام واستراتيجية التحكم المناسبين قبل الالتزام بالميزانية.'),
        intro=('Cooling is usually the largest running cost in a Saudi building. The consultancy checks the load, compares system options and plans the work so that the design, the equipment and the maintenance all point the same way.',
               'التبريد هو غالباً أكبر تكلفة تشغيل في المبنى السعودي. تفحص الاستشارة الأحمال وتقارن خيارات الأنظمة وتخطط العمل بحيث يتسق التصميم مع المعدات والصيانة.'),
        covers=[
            (('Load calculation review', 'مراجعة حسابات الأحمال'), ('Cooling and ventilation loads checked against real usage rather than rule-of-thumb.', 'فحص أحمال التبريد والتهوية وفق الاستخدام الفعلي لا التقدير التقريبي.')),
            (('System selection', 'اختيار النظام'), ('VRF/VRV, chilled water and packaged options compared for your building and zoning.', 'مقارنة أنظمة VRF/VRV والمياه المبردة والوحدات المجمّعة لمبناك وتقسيم مناطقه.')),
            (('Energy and controls', 'الطاقة والتحكم'), ('Where controls and BMS integration can cut running cost.', 'المواضع التي يمكن للتحكم والربط مع نظام إدارة المبنى أن يخفض فيها تكلفة التشغيل.')),
            (('Retrofit or replace', 'التحديث أم الاستبدال'), ('Whether to refurbish existing plant or replace it, with the cost logic shown.', 'هل تُجدَّد المعدات القائمة أم تُستبدل، مع إظهار منطق التكلفة.')),
            (('Maintenance planning', 'تخطيط الصيانة'), ('A preventive maintenance routine sized to the system and the building.', 'برنامج صيانة وقائية مناسب للنظام والمبنى.')),
        ],
        service=('/services/hvac-solutions/', ('HVAC Solutions', 'حلول التكييف')),
        q=(('Can you review a system that is already installed?', 'هل يمكنكم مراجعة نظام مركّب بالفعل؟'),
           ('Yes. We can review an existing system and its running pattern and advise on optimisation, refurbishment or replacement.',
            'نعم. يمكننا مراجعة نظام قائم ونمط تشغيله وتقديم المشورة بشأن التحسين أو التجديد أو الاستبدال.')),
        wa=('HVAC consultancy', 'استشارة التكييف'),
    ),
    'isolated-power': dict(
        name=('Isolated Power Panels (IPP)', 'لوحات الطاقة المعزولة (IPP)'),
        meta_title=('Isolated Power Panel Consultancy Saudi Arabia | NFPA 99 Plan', 'استشارات لوحات الطاقة المعزولة في السعودية | خطة NFPA 99'),
        meta_desc=('Paid isolated power panel (IPP) consultancy for hospitals in Saudi Arabia: where IPP is needed, NFPA 99 requirements, layout and a plan with reference costing.',
                   'استشارات مدفوعة للوحات الطاقة المعزولة (IPP) في المستشفيات بالسعودية: أماكن الحاجة ومتطلبات NFPA 99 والتوزيع وخطة مع تكلفة مرجعية.'),
        h1=('Isolated Power Panel Consultancy for Hospitals', 'استشارات لوحات الطاقة المعزولة للمستشفيات'),
        sub=('Know where isolated power is needed, and plan it with the rest of the room.', 'اعرف أين تلزم الطاقة المعزولة، وخطّط لها مع بقية الغرفة.'),
        intro=('Isolated power protects patients and continuity in wet procedure locations and critical care. The consultancy establishes where it is required, how it should be laid out and how it fits with the room, the UPS and the rest of the electrical design.',
               'تحمي الطاقة المعزولة المرضى واستمرارية العمل في أماكن الإجراءات الرطبة والعناية الحرجة. تحدد الاستشارة أين تلزم وكيف تُوزَّع وكيف تنسجم مع الغرفة ونظام UPS وبقية التصميم الكهربائي.'),
        covers=[
            (('Where IPP is required', 'أين تلزم لوحات IPP'), ('Which rooms and locations need isolated power, and which do not.', 'أي الغرف والمواقع تحتاج طاقة معزولة وأيها لا تحتاج.')),
            (('NFPA 99 requirements', 'متطلبات NFPA 99'), ('The standards that apply to the installation, explained in plain terms.', 'المعايير المطبقة على التركيب موضحة بلغة واضحة.')),
            (('Sizing and layout', 'الحجم والتوزيع'), ('Panel capacity, circuits and monitoring arranged for each operating room or unit.', 'سعة اللوحات والدوائر والمراقبة لكل غرفة عمليات أو وحدة.')),
            (('Coordination with OR, UPS and HVAC', 'التنسيق مع غرفة العمليات وUPS والتكييف'), ('The electrical, UPS and environmental scopes lined up so they do not clash on site.', 'مواءمة نطاقات الكهرباء وUPS والبيئة حتى لا تتعارض في الموقع.')),
            (('Testing and maintenance plan', 'خطة الاختبار والصيانة'), ('Routine testing of the monitoring equipment and a record-keeping approach.', 'اختبار دوري لأجهزة المراقبة وأسلوب لحفظ السجلات.')),
        ],
        service=('/services/isolated-power-panels/', ('Isolated Power Panels', 'لوحات الطاقة المعزولة')),
        q=(('Can the consultancy cover a new hospital wing?', 'هل تشمل الاستشارة جناحاً جديداً في مستشفى؟'),
           ('Yes. It can be done at design stage for a new wing or as a review of an existing room, depending on your project.',
            'نعم. يمكن إجراؤها في مرحلة التصميم لجناح جديد أو كمراجعة لغرفة قائمة، بحسب مشروعك.')),
        wa=('isolated power panel consultancy', 'استشارة لوحات الطاقة المعزولة'),
    ),
    'facility-management': dict(
        name=('Facility Management', 'إدارة المرافق'),
        meta_title=('Facility Management Consultancy Saudi Arabia | Maintenance Plan', 'استشارات إدارة المرافق في السعودية | خطة الصيانة'),
        meta_desc=('Paid facility management consultancy in Saudi Arabia: asset and maintenance review, service scope, lifecycle budget and a plan with reference costing.',
                   'استشارات مدفوعة لإدارة المرافق في السعودية: مراجعة الأصول والصيانة ونطاق الخدمة وميزانية دورة الحياة وخطة مع تكلفة مرجعية.'),
        h1=('Facility Management Consultancy', 'استشارات إدارة المرافق'),
        sub=('See where maintenance money is going, and plan spending across the life of your assets.', 'اعرف أين تذهب أموال الصيانة، وخطّط للإنفاق على مدى عمر أصولك.'),
        intro=('Running a facility well is a planning problem as much as a technical one. The consultancy looks at your assets, your maintenance arrangements and your budget, and sets out a plan that is realistic for the site.',
               'إدارة المرفق بنجاح مسألة تخطيط بقدر ما هي مسألة فنية. تنظر الاستشارة في أصولك وترتيبات الصيانة وميزانيتك وتضع خطة واقعية للموقع.'),
        covers=[
            (('Asset and condition review', 'مراجعة الأصول وحالتها'), ('What you have, what condition it is in, and what is nearing end of life.', 'ما لديك وحالته وما يقترب من نهاية عمره.')),
            (('Preventive maintenance planning', 'تخطيط الصيانة الوقائية'), ('A maintenance routine by discipline, with frequencies that match the equipment.', 'برنامج صيانة لكل تخصص بدورات تناسب المعدات.')),
            (('Service scope and contracts', 'نطاق الخدمة والعقود'), ('What to put in a maintenance contract, and what to ask for from contractors.', 'ما يجب إدراجه في عقد الصيانة وما يُطلب من المقاولين.')),
            (('Cost and energy review', 'مراجعة التكلفة والطاقة'), ('Where running costs sit and where they can realistically come down.', 'أين تقع تكاليف التشغيل وأين يمكن خفضها بشكل واقعي.')),
            (('Lifecycle budget', 'ميزانية دورة الحياة'), ('Replacement and refurbishment planned over several years instead of as emergencies.', 'تخطيط الاستبدال والتجديد على عدة سنوات بدلاً من معالجته كحالات طارئة.')),
        ],
        service=('/services.html', ('All Services', 'جميع الخدمات')),
        q=(('Does the consultancy cover several disciplines at once?', 'هل تشمل الاستشارة عدة تخصصات معاً؟'),
           ('Yes. Facility management usually spans electrical, UPS, HVAC and fire systems, and the plan can cover them together.',
            'نعم. تشمل إدارة المرافق عادة الكهرباء وUPS والتكييف وأنظمة الحريق، ويمكن للخطة أن تغطيها معاً.')),
        wa=('facility management consultancy', 'استشارة إدارة المرافق'),
    ),
    'airports': dict(
        name=('Airports', 'المطارات'),
        meta_title=('Airport Facility Consultancy Saudi Arabia | Power, Lighting & Fire', 'استشارات منشآت المطارات في السعودية | الطاقة والإضاءة والحريق'),
        meta_desc=('Paid consultancy for airport facilities in Saudi Arabia: resilient power, aviation lighting, fire protection and HVAC, with a phased project plan and reference costing.',
                   'استشارات مدفوعة لمنشآت المطارات في السعودية: طاقة موثوقة وإضاءة ملاحية وحماية من الحريق وتكييف مع خطة مرحلية وتكلفة مرجعية.'),
        h1=('Consultancy for Airport Facilities', 'استشارات لمنشآت المطارات'),
        sub=('Plan upgrades that keep operations running, with the cost laid out.', 'خطّط للترقيات مع استمرار التشغيل، مع بيان التكلفة.'),
        intro=('Airport facilities cannot simply be switched off for a project. The consultancy looks at the systems that keep a terminal or airfield running and plans upgrades in stages that respect live operations.',
               'لا يمكن إيقاف منشآت المطار ببساطة من أجل مشروع. تنظر الاستشارة في الأنظمة التي تُبقي المبنى أو المدرج عاملاً وتخطط للترقيات على مراحل تراعي التشغيل الفعلي.'),
        covers=[
            (('Resilient power', 'الطاقة الموثوقة'), ('UPS, distribution and backup arrangements for critical airport loads.', 'ترتيبات UPS والتوزيع والطاقة الاحتياطية لأحمال المطار الحرجة.')),
            (('Aviation and facility lighting', 'الإضاءة الملاحية وإضاءة المرافق'), ('Obstruction, helipad and general lighting reviewed for performance and upkeep.', 'مراجعة إضاءة العوائق ومهابط الطائرات المروحية والإضاءة العامة من حيث الأداء والصيانة.')),
            (('Fire protection', 'الحماية من الحريق'), ('Detection and suppression suited to terminals, plant rooms and support buildings.', 'كشف وإطفاء مناسبان للمباني ومحطات التشغيل والمباني المساندة.')),
            (('HVAC for large spaces', 'التكييف للمساحات الكبيرة'), ('Cooling strategy for terminals and public areas, with running cost in view.', 'استراتيجية تبريد للمباني والمناطق العامة مع مراعاة تكلفة التشغيل.')),
            (('Phased delivery under live operations', 'التنفيذ على مراحل أثناء التشغيل'), ('A staged plan that limits disruption and shows the cost of each phase.', 'خطة مرحلية تحد من التعطل وتبيّن تكلفة كل مرحلة.')),
        ],
        service=('/solutions/aviation/', ('Aviation Solutions', 'حلول قطاع الطيران')),
        q=(('Which airport systems can the consultancy look at?', 'ما أنظمة المطار التي يمكن للاستشارة أن تشملها؟'),
           ('Power backup, lighting, fire protection and HVAC are the main areas, chosen according to what your facility needs. The scope is agreed in writing.',
            'الطاقة الاحتياطية والإضاءة والحماية من الحريق والتكييف هي المجالات الرئيسية، وتُختار بحسب احتياج منشأتك. ويُتفق على النطاق كتابياً.')),
        wa=('airport facility consultancy', 'استشارة منشآت المطارات'),
    ),
}

# Policy page ---------------------------------------------------------------------
POLICY_META = (
    ('Consultancy Policy | Black Arrow Venture', 'سياسة الاستشارات | بلاك أرو فنتشر'),
    ('The terms on which Black Arrow provides paid technical consultancy: scope, fees, deliverables, reference costing, responsibilities and governing law.',
     'الشروط التي تقدم بموجبها بلاك أرو الاستشارات الفنية المدفوعة: النطاق والأتعاب والمخرجات والتكلفة المرجعية والمسؤوليات والنظام الواجب التطبيق.'),
)
POLICY = [
    ('cp_h1', ('Consultancy Policy', 'سياسة الاستشارات'), None),
    ('cp_sub', ('The terms on which we provide paid technical consultancy.', 'الشروط التي نقدم بموجبها الاستشارات الفنية المدفوعة.'), None),
    ('cp_intro', ('This policy applies to technical consultancy services provided by Black Arrow Venture company (“Black Arrow”, “we”) to a client (“you”) in the sectors listed on our Technical Consultancy pages. It should be read with our Terms of Service and Privacy Policy. Nothing in it limits any right you have under the laws of the Kingdom of Saudi Arabia that cannot lawfully be limited.',
                  'تسري هذه السياسة على خدمات الاستشارات الفنية التي تقدمها شركة بلاك أرو فنتشر (“بلاك أرو”، “نحن”) للعميل (“أنت”) في القطاعات المذكورة في صفحات الاستشارات الفنية لدينا. وتُقرأ مع شروط الخدمة وسياسة الخصوصية. ولا شيء فيها يحد من أي حق لك بموجب أنظمة المملكة العربية السعودية لا يجوز تقييده نظاماً.'), None),
    ('cp_h_nature', ('1. Nature of the service', '1. طبيعة الخدمة'), None),
    ('cp_nature', ('Consultancy is advice and planning. It is a paid service, not a free assessment. It does not include supply, installation or construction unless a separate written agreement says so.',
                   'الاستشارة نصح وتخطيط. وهي خدمة مدفوعة وليست تقييماً مجانياً. ولا تشمل التوريد أو التركيب أو التنفيذ ما لم يوجد اتفاق كتابي منفصل بذلك.'), None),
    ('cp_h_scope', ('2. Scope, quotation and acceptance', '2. النطاق وعرض السعر والقبول'), None),
    ('cp_scope', ('The scope and the fee depend on your site, your sector, the size of the facility and the stage of the project. After we receive your request we send a written quotation stating the scope, the deliverables, the fee, the payment terms and any assumptions. Work starts only when you accept the quotation in writing. Requests to change the scope are agreed in writing and may change the fee.',
                  'يعتمد النطاق والأتعاب على موقعك وقطاعك وحجم المنشأة ومرحلة المشروع. وبعد استلام طلبك نرسل عرض سعر مكتوباً يبين النطاق والمخرجات والأتعاب وشروط الدفع وأي افتراضات. ولا يبدأ العمل إلا بقبولك عرض السعر كتابياً. ويُتفق كتابياً على أي طلب لتغيير النطاق وقد يؤدي إلى تغيير الأتعاب.'), None),
    ('cp_h_fees', ('3. Fees and payment', '3. الأتعاب والدفع'), None),
    ('cp_fees', ('Fees are stated in Saudi riyals in the quotation. Value added tax is added where the law requires it. Payment terms, including any advance payment or milestones, are set out in the quotation. Fees are payable for the work performed even where you decide not to proceed with the project the plan describes.',
                 'تُذكر الأتعاب بالريال السعودي في عرض السعر. وتُضاف ضريبة القيمة المضافة حيثما يتطلب النظام ذلك. وتُحدد شروط الدفع، ومنها أي دفعة مقدمة أو دفعات مرحلية، في عرض السعر. وتستحق الأتعاب عن العمل المنجز حتى لو قررت عدم المضي في المشروع الذي تصفه الخطة.'), None),
    ('cp_h_deliv', ('4. Deliverables', '4. المخرجات'), None),
    ('cp_deliv', ('Unless the quotation says otherwise, deliverables are a written report, a start-to-finish project plan, a reference costing and a description of the method and assumptions used. You may use them for the project they were prepared for, including with other contractors. They may not be resold or presented as your own professional work without our written permission.',
                  'ما لم يذكر عرض السعر خلاف ذلك، فإن المخرجات هي تقرير مكتوب وخطة مشروع من البداية إلى النهاية وتكلفة مرجعية ووصف للمنهجية والافتراضات المستخدمة. ويجوز لك استخدامها للمشروع الذي أُعدت له، ومنه مع مقاولين آخرين. ولا يجوز إعادة بيعها أو تقديمها على أنها عمل مهني خاص بك دون إذن كتابي منا.'), None),
    ('cp_h_cost', ('5. Reference costing', '5. التكلفة المرجعية'), None),
    ('cp_cost', ('Reference costing is an indicative estimate for planning and budgeting, prepared from the information available when it was written. Market prices, exchange rates, site conditions and scope can change it. It is not an offer and is not binding. A binding price arises only from a signed contract or a purchase order accepted by us in writing.',
                 'التكلفة المرجعية تقدير استرشادي للتخطيط وإعداد الميزانية، يُعدّ من المعلومات المتاحة وقت كتابته. وقد تغيّره أسعار السوق وأسعار الصرف وظروف الموقع والنطاق. وهو ليس عرضاً وليس ملزماً. ولا ينشأ سعر ملزم إلا من عقد موقع أو أمر شراء نقبله كتابياً.'), None),
    ('cp_h_results', ('6. No guarantee of results', '6. عدم ضمان النتائج'), None),
    ('cp_results', ('We prepare our advice with reasonable skill and care. Savings, energy reductions, timelines and outcomes depend on factors outside our control, so we do not guarantee any specific saving or result.',
                    'نعد مشورتنا بالمهارة والعناية المعقولتين. وتعتمد الوفورات وخفض الطاقة والجداول الزمنية والنتائج على عوامل خارجة عن سيطرتنا، لذلك لا نضمن أي وفر أو نتيجة محددة.'), None),
    ('cp_h_reg', ('7. Standards, approvals and regulated work', '7. المعايير والموافقات والأعمال المنظمة'), None),
    ('cp_reg', ('Our advice refers to applicable standards and codes, for example NFPA, ASHRAE and Saudi requirements. It is not an approval, certification or licence by any authority. Where a project needs approval from an authority, or work that must be signed off by a licensed engineering office or contractor, we will say so in the quotation or report, and obtaining it remains your responsibility unless we agree otherwise in writing.',
                 'تشير مشورتنا إلى المعايير والأكواد المطبقة، ومنها NFPA وASHRAE والمتطلبات السعودية. وهي ليست موافقة أو شهادة أو ترخيصاً من أي جهة. وعندما يحتاج مشروع إلى موافقة جهة مختصة أو إلى أعمال يجب أن يعتمدها مكتب هندسي أو مقاول مرخص، فسنبيّن ذلك في عرض السعر أو التقرير، ويبقى الحصول عليه مسؤوليتك ما لم نتفق كتابياً على خلاف ذلك.'), None),
    ('cp_h_resp', ('8. Your responsibilities', '8. مسؤولياتك'), None),
    ('cp_resp', ('You agree to give us accurate and complete information, access to the site and documents where the scope needs them, and timely decisions. Delays or inaccurate information may change the timeline, the findings and the fee.',
                 'توافق على تزويدنا بمعلومات دقيقة وكاملة وبإمكانية الوصول إلى الموقع والمستندات حيثما يتطلب النطاق ذلك، وعلى اتخاذ القرارات في الوقت المناسب. وقد يؤدي التأخير أو عدم دقة المعلومات إلى تغيير الجدول الزمني والنتائج والأتعاب.'), None),
    ('cp_h_indep', ('9. Disclosure of our interests', '9. الإفصاح عن مصالحنا'), None),
    ('cp_indep', ('Black Arrow also supplies and installs some equipment and services in these sectors. Where a recommendation involves a product or service that Black Arrow supplies, the report will say so. You are under no obligation to buy equipment, installation or maintenance from us, and you may use the plan with any other contractor.',
                  'تقوم بلاك أرو أيضاً بتوريد وتركيب بعض المعدات والخدمات في هذه القطاعات. وعندما تتعلق التوصية بمنتج أو خدمة توفرها بلاك أرو، يذكر التقرير ذلك. ولا يترتب عليك أي التزام بشراء المعدات أو التركيب أو الصيانة منا، ويمكنك استخدام الخطة مع أي مقاول آخر.'), None),
    ('cp_h_conf', ('10. Confidentiality', '10. السرية'), None),
    ('cp_conf', ('We treat the information you give us and the deliverables as confidential and use them only to provide the service, except where disclosure is required by law or by a competent authority.',
                 'نتعامل مع المعلومات التي تزودنا بها ومع المخرجات على أنها سرية ولا نستخدمها إلا لتقديم الخدمة، إلا إذا اقتضى النظام أو جهة مختصة الإفصاح عنها.'), None),
    ('cp_h_cancel', ('11. Cancellation', '11. الإلغاء'), None),
    ('cp_cancel', ('You may cancel before work starts by telling us in writing. If you cancel after work has started, you pay for the work performed and costs incurred up to that point, as stated in the quotation.',
                   'يجوز لك الإلغاء قبل بدء العمل بإبلاغنا كتابياً. وإذا ألغيت بعد بدء العمل فإنك تدفع مقابل العمل المنجز والتكاليف المتكبدة حتى ذلك الوقت، وفق ما يبينه عرض السعر.'), None),
    ('cp_h_liab', ('12. Limitation of liability', '12. حدود المسؤولية'), None),
    ('cp_liab', ('To the fullest extent permitted by Saudi law, our liability arising from the consultancy is limited to the fees you paid for it, and we are not liable for indirect or consequential loss. Nothing here limits liability that cannot lawfully be limited.',
                 'إلى أقصى حد يسمح به النظام السعودي، تقتصر مسؤوليتنا الناشئة عن الاستشارة على الأتعاب التي دفعتها عنها، ولا نتحمل الخسائر غير المباشرة أو التبعية. ولا شيء هنا يحد من مسؤولية لا يجوز نظاماً الحد منها.'), None),
    ('cp_h_data', ('13. Personal data', '13. البيانات الشخصية'), None),
    ('cp_data', ('We handle personal data in line with our <a href="/privacy-policy.html">Privacy Policy</a> and the applicable Saudi personal data protection requirements.',
                 'نتعامل مع البيانات الشخصية وفق <a href="/ar/privacy-policy.html">سياسة الخصوصية</a> لدينا ومتطلبات حماية البيانات الشخصية المطبقة في المملكة.'), 'html'),
    ('cp_h_law', ('14. Governing law and disputes', '14. النظام الواجب التطبيق والمنازعات'), None),
    ('cp_law', ('This policy and any consultancy engagement are governed by the laws of the Kingdom of Saudi Arabia. We will try to resolve any dispute amicably first. Failing that, the courts of the Kingdom have exclusive jurisdiction.',
                'تخضع هذه السياسة وأي ارتباط استشاري لأنظمة المملكة العربية السعودية. وسنسعى أولاً إلى حل أي نزاع ودياً. وإن تعذر ذلك فلمحاكم المملكة الاختصاص القضائي الحصري.'), None),
    ('cp_updated', ('<strong>Last updated:</strong> 21 September 2026', '<strong>آخر تحديث:</strong> 21 سبتمبر 2026'), 'html'),
]
